server/src/http/routes/rcoFormation.js
server/src/http/server.js

New api route to retrieve rco formations :
**e.g:** GET `http://<host>/api/rcoformation/items?query={"published":true}`

feat: add rco formations api route

---

server/src/jobs/rcoConverter/converter/converter.js
server/src/jobs/rcoImporter/tests/importer_db_operations__test.js
server/src/jobs/trainingsUpdater/tests/updater.test.js
server/src/jobs/trainingsUpdater/updater/updater.js

perf: Faster updater & converter

---

server/src/jobs/oneshot/pSupTemporary/controller.js

faster & without memory trouble

fix: psup load script the mongo way

---

server/src/jobs/rcoConverter/converter/converter.js
server/src/jobs/rcoDiff/diff/diff.js
server/src/jobs/rcoImporter/importer/importer.js
server/src/jobs/trainingsUpdater/updater/updater.js

Too large to be store as a single mongo document

fix: deactivate save reports in db

---

server/config/default.json
server/src/jobs/clean/cleanLogs.js
server/src/jobs/clean/cleanReports.js
server/src/jobs/clean/index.js
server/src/jobs/index.js
server/src/jobs/rcoConverter/converter/converter.js
server/src/jobs/trainingsUpdater/updater/updater.js

Clean reports and logs every night along with the cron job (server_jobs.sh / yarn jobs).
To start with, keep last 30 days.

feat: clean reports & logs

---

server/package.json
server/src/common/model/schema/psFormation.js
server/src/jobs/oneshot/psFormation/bulkUpdate.js
server/src/jobs/oneshot/psFormation/index.js
server/src/jobs/oneshot/psFormation/loadPsFormation.js
server/src/jobs/oneshot/psFormation/updateMatching.js
ui/src/pages/reconciliation/components/Accordion.js

* feat: oneshot bulk psformation update
* fix: add enum value mapping_etat_reconciliation
* fix : update object declaration
* fix: tree shaking
* fix : query regex & code readability
* feat: add db load & script

psformation oneshot script (#42)

---

ui/src/pages/Search/components/ExportButton.js

fix: display progress in search export

---

server/package.json
server/src/jobs/afReference/controller.js
server/src/jobs/afReference/index.js
server/src/jobs/common/utils/referenceUtils.js
server/src/jobs/index.js
server/src/jobs/psReference/controller.js

En appliquant les mêmes règles que l'année dernière pour le statut "à publier".

feat: Affelnet reference & pertinence script

---

server/package.json
server/src/jobs/oneshot/afFormation/importer.js
server/src/jobs/oneshot/afFormation/index.js
server/yarn.lock

Utilisation de la lib [oleoduc](https://www.npmjs.com/package/oleoduc) de @bguerout, que je remercie pour son aide 🙌🏻

Fix: affelnet importer

---

server/src/jobs/afFormation/afcoverage.js
server/src/jobs/afFormation/afcoverageEtablissement.js
server/src/jobs/afFormation/index.js

* fix: uai calls
* fix: control logic
* fix: execution & advance query filtre

Hotfix: coverage (#118)

---

ui/src/pages/Formation/Formation.js

feat: publish popin v2

---

server/src/jobs/afFormation/afcoverage.js
server/src/jobs/afFormation/afcoverageEtablissement.js
server/src/jobs/afFormation/index.js
server/src/jobs/afFormation/matcher.js

Problème de séquence identifié à la fin du coverage ce matin

fix: coverage

---

ui/src/pages/Formation/Formation.js

chore(ui): update publish popin style

---

server/src/common/model/index.js
server/src/common/model/schema/etablissement.js
server/src/common/model/schema/index.js
server/src/http/routes/affelnet.js
server/src/http/routes/parcoursup.js
server/src/jobs/afFormation/afcoverageEtablissement.js
ui/src/pages/reconciliation-affelnet/components/Accordion.js
ui/src/pages/reconciliation-affelnet/index.js

Bulk import of establishment data using `yarn etablissement:dump`

Feat: etablissement on catalogue

---

ui/src/pages/Formation/Formation.js

feat(ui): human readable display of dates

---

.github/workflows/yarn-ci-server.yml
docker-compose.override.yml
server/Dockerfile
server/package.json
server/src/common/services/tables_correspondance.js
server/src/jobs/afFormation/afcoverage.js
server/src/jobs/oneshot/afFormation/importer.js
server/src/logic/mappers/codePostalMapper.js
server/yarn.lock

This implies some configuration steps :

feat: plug JS lib tables correspondance

---

server/src/common/model/schema/mnaFormation/etablissement.formateur.sub.js
server/src/common/model/schema/mnaFormation/etablissement.gestionnaire.sub.js
server/src/common/model/schema/mnaFormation/etablissement.reference.sub.js
server/src/logic/mappers/etablissementsMapper.js

feat: add etablissement creation date

---

server/src/common/model/schema/etablissement.js
server/src/jobs/afFormation/index.js
server/src/jobs/afFormation/reconciliation.js
server/src/jobs/index.js

Afin que tout tourne automatiquement :)

chore: reorder nightly scripts

---

ui/src/pages/HomePage.js
ui/src/pages/LoginPage.js
ui/src/pages/Search/Search.js
ui/src/pages/Search/search.css
ui/src/pages/password/ForgottenPasswordPage.js
ui/src/pages/password/ResetPasswordPage.js

fix(ui): clean some ui on mobile

---

server/src/common/model/schema/mnaFormation/mnaFormation.js
server/src/common/model/swaggerSchema/mnaFormation.js
server/src/http/routes/convertedFormationSecure.js
server/src/jobs/afReference/controller.js
server/src/jobs/psReference/controller.js
ui/src/common/components/StatusBadge.jsx
ui/src/pages/Formation/Formation.js

:sparkles: "à publier (soumis à validation)"
https://trello.com/c/KGj1QbCM/333-affelnet-mise-%C3%A0-jour-des-r%C3%A8gles-de-pertinence-nouveau-statut-soumis-%C3%A0-validation

feat: New formation status

---

ui/src/pages/Etablissement/Etablissement.js

feat: update before save etablissement

---

server/src/common/model/schema/mnaFormation/mnaFormation.js
server/src/common/model/swaggerSchema/mnaFormation.js
server/src/jobs/afFormation/afcoverage.js
server/src/jobs/afFormation/reconciliation.js
server/src/logic/controller/reconciliation.js

:sparkles: code_nature & secteur

feat: add extra fields for affelnet when possible

---

server/src/jobs/pertinence/affelnet/controller.js
server/src/jobs/pertinence/parcoursup/controller.js
server/src/jobs/reference/affelnet/controller.js
server/src/jobs/reference/parcoursup/controller.js

so that it doesn't fill in Affelnet or Parcoursup

feat: exclude catalog non eligible from pertinence/reference

---

server/src/common/model/index.js
server/src/common/model/schema/mnaFormation/mnaFormation.js
server/src/common/model/swaggerSchema/mnaFormation.js
server/src/jobs/common/utils/referenceUtils.js
server/src/jobs/pertinence/affelnet/controller.js
server/src/jobs/pertinence/affelnet/rules.js
server/src/jobs/pertinence/parcoursup/controller.js
server/src/jobs/pertinence/parcoursup/rules.js
server/src/logic/controller/reconciliation.js
server/src/logic/updaters/mnaFormationUpdater.js

:information_source:  Using a temporary sandbox collection to apply pertinence rules and find the corresponding mefs.

feat(affelnet): Autofill consistant mef for affelnet

---

server/src/common/esClient/mongoosastic/index.js

so that mefs10 can be exported

fix: update eS mapping for nested fields

---

server/src/constants/certificateurs.js
server/src/logic/mappers/etablissementsMapper.js
ui/src/constants/certificateurs.js
ui/src/pages/Formation/Formation.js

* show message if cfd is outdated
* don't show partners in case of certificateur "Ministère du travail"

feat: update training sheet

---

server/src/logic/controller/reconciliation.js
ui/src/common/components/formation/PublishModal.jsx

feat: prefill affelnet_infos_offre with data from reconciliation

---

server/src/jobs/trainingsUpdater/updater/updater.js
ui/src/common/components/report/Tabs.jsx

chore: clean update report

---

server/src/jobs/pertinence/affelnet/rules.js
server/src/logic/updaters/mnaFormationUpdater.js

https://trello.com/c/4xujDUNk/441-spec-compl%C3%A9mentaire-p%C3%A9rim%C3%A8tre-af

chore: update affelnet rules

---

server/src/jobs/reference/affelnet/controller.js
server/src/jobs/reference/parcoursup/controller.js

:zap: ~ 30s for Ps, ~ 5 min for Af

perf(reference): faster reference jobs

---

server/src/common/components/stats.js
ui/src/pages/Dashboard/index.js

feat: diplomes stats

---

ui/src/App.js
ui/src/common/components/StatGrid.jsx
ui/src/pages/Dashboard/index.js
ui/src/pages/admin/TagsHistory.js

quick & dirty first implementation
à reprendre, mais ça donne une bonne idée de comment faire :wink: 
:warning: penser à changer la target branch quand l'historique sera mergé

feat: tags history page

---

server/src/logic/updaters/mnaFormationUpdater.js

https://trello.com/c/vNqVYG3e/460-pourquoi-sur-cette-formation-cest-le-cap-en-1-an-qui-sort-alors-que-lof-me-dit-quil-ne-fait-que-du-cap-en-2-ans-https-cataloguea

fix: update info offre label

---

server/config/default.json
server/src/common/components/components.js
server/src/common/services/tables_correspondance.js
server/src/http/routes/affelnet.js
server/src/http/routes/parcoursup.js
server/src/jobs/index.js
server/src/jobs/oneshot/afFormation/importer.js
server/src/jobs/parcoursup/2020/importer.js
server/src/jobs/parcoursup/2021/importer.js
server/src/jobs/parcoursup/miscJobs/differentiel-2020_2021.js
server/src/jobs/parcoursup/miscJobs/get-rncp-romes-cfd.js
server/src/jobs/tcoSdkPlayground/index.js
server/src/logic/controller/coverage.js
server/src/logic/mappers/cfdMapper.js

Also init tco model only once :)

chore: use tco sdk for getCfdInfo & getMef10Info

---

server/src/http/routes/convertedFormation.js

hoftix: patch api because request from Affelnet is not JSON valid

---

ui/src/pages/layout/components/Footer.js

@see https://github.com/mission-apprentissage/catalogue-apprentissage/pull/238

fix: RGAA compliance step 1

---

server/src/jobs/parcoursup/2021/importer.js

Prise en compte des formations existantes + import fichier depuis S3

456: ajustement du script d'import PSUP 2021

---

README.md

chore: fixing readme title

---

server/src/common/model/swaggerSchema/mnaFormation.js
server/src/http/routes/affelnet.js
server/src/http/routes/parcoursup.js
ui/src/pages/reconciliation-affelnet/index.js
ui/src/pages/reconciliation-parcoursup/index.js

J'ai vu qu'il avait eu un petit bug sur le calcule des pourcentages. Voila mon fix

fix: reconciled pourcentage

---

ui/package.json
ui/yarn.lock

J'ai add dans /ui le husky et le lint-staged

fix: add husky and lint-staged /ui

---

ui/src/pages/Search/constantsRCOFormations.js

Come on Excel, utf-8 is is set as the encoding of the file...

fix(export): rm accents since MS Excel is not able to read them properly

---

ui/src/pages/Etablissement/Etablissement.js
ui/src/pages/Search/Search.js

Ajout du nombre de formations dans le catalogue sur la fiche établissement + lien vers la page de recherche pré-filtrée

feat: add trainings count & link in establishment page

---

server/src/common/model/schema/mnaFormation/mnaFormation.js
server/src/common/model/swaggerSchema/mnaFormation.js
ui/src/common/components/formation/PublishModal.jsx

Formulaire pour saisir la raison de non publication d'une formation (pourtant dans le périmètre) sur Affelnet

feat(affelnet): unpublish form cause

---

ui/package.json
ui/setupTests.js
ui/src/App.test.js
ui/src/common/utils/testUtils.js
ui/src/pages/HomePage.js
ui/src/pages/HomePage.test.js
ui/yarn.lock

Setup des tests front, avec **react-testing-library** & **msw** pour les mocks API.
```bash
$> cd ui/
$> yarn test
```

Tech/setup UI tests

---

server/package.json
server/src/jobs/tcoSdkPlayground/index.js
server/src/logic/updaters/mnaFormationUpdater.js
server/yarn.lock

Récupération des coordonnées de geoloc des lieux de formations depuis l'api adresse.
En cas de plusieurs geoloc trouvées, les coordonnées du lieu de formation ne sont pas mises à jour.
**n.b:** Au moment de la mep, à lancer 1 fois : le script `trainings:updater` avec l'option `--withCodePostal`.
https://trello.com/c/hUFNr8fy/496-lba-add-geo-info-geocoord-sur-les-lieux-de-formations

feat(updater): lieu_formation get geo coordinates from address

---

server/src/logic/updaters/mnaFormationUpdater.js

fix(geoloc): use idea_geo_coordonnees_etablissement field

---

docker-compose.override.yml
ui/Dockerfile.dev

```
Building ui
[+] Building 123.7s (10/10) FINISHED 
```

feat: local dockerfile env to speed up boot

---

server/src/common/model/index.js
server/src/common/model/schema/index.js
server/src/common/model/schema/statistique.js
server/src/http/routes/stats.js

endpoint : /api/stats — POST
expected payload :
```
source: String
id_rco_formation: String
```
return OK ou error si l'un des deux est manquant

feat: gather stats from external source

---

server/src/http/routes/upload.js
server/src/jobs/oneshot/afFormation/importer.js
server/src/jobs/oneshot/afFormation/index.js
server/src/logic/controller/coverage.js
server/src/logic/controller/reconciliation.js
ui/src/pages/admin/UploadFiles.js

with upload & matching improved

feat(affelnet): import 2021

---

server/src/logic/controller/coverage.js

fix(affelnet): Fix Corsica coverage

---

ui/src/common/components/formation/PublishModal.jsx

chore(ui): new design publish modal

---

ui/src/pages/admin/Users.js

fix: user creation academieList exception

---

server/src/jobs/pertinence/affelnet/README.md

doc(affelnet): doc pertinence

---

ui/src/common/components/Search/components/CardListPsFormations/CardListPsFormations.js
ui/src/common/components/Search/constantsReconciliationPS.js
ui/src/common/components/StatusBadge.jsx
ui/src/common/components/reconciliation/Compare.jsx
ui/src/pages/ActionsExpertes/ActionsExpertes.jsx
ui/src/pages/admin/ReconciliationPs.js
ui/src/pages/layout/components/Header.js
ui/src/theme/components/badge.js
ui/src/theme/components/text.js

cosmetics
https://trello.com/c/eYVYgRfb/588-recette-ui-reconciliation

feat: review Ui reconciliation

---

docker-compose.yml
ui/src/common/components/Search/components/QueryBuilder/index.js
ui/src/common/components/Search/components/QueryBuilder/utils.js

Hey :), la mise a jour de elastic est opérationnel. Pouvez-vous tester ça pour voir si tout marche ? merci

feat: mise a jour elastic version

---

server/src/jobs/oneshot/rcoCheck/index.js

Après moultes essais de requêtes géospatiales infructueuses via Mongo, je me suis résigné à écrire une implémentation JS :wink:

feat: Check RCO data : find geoloc gaps

---

server/package.json
server/src/jobs/index.js
server/yarn.lock

@antoinebigard J'ai l'impression qu'on ne faisait plus la maj des adresses des formations converties suite à la refacto :eyes:

fix: run updater with cp update after converter

---

server/src/common/utils/rulesUtils.js

Pour Parcoursup : Le contrôle titre ou Tp actif est systématique, il est maintenant automatisé.
On pourra donc supprimer les règles "Titre ou TP actif".

feat(perimetre): auto check for active rncp

---

server/src/http/middlewares/logMiddleware.js

fix(es): no body in logs since it is impossible to read

---

server/src/jobs/EtablissementsUpdater/index.js

Avoid updates on 272 closed establishment every night :slightly_smiling_face:

perf: by default update only open establishments

---

server/package.json
server/src/common/components/catalogue.js
server/src/jobs/EtablissementsUpdater/tests/updater.test.js
server/src/jobs/EtablissementsUpdater/updater/updater.js
server/src/logic/updaters/etablissementUpdater.js
server/yarn.lock

perf: use etablissement service from sdk

---

ui/src/common/components/Search/constantsReconciliationPS.js

Rapprochement / onglet validés / filtres par statuts : problème de rafraîchissement de compteurs et de liste filtrée

fix: filters by status

---

server/src/jobs/index.js

**setup-vm** required for recette & prod

feat: add env var to skip rco import when needed

---

server/src/jobs/parcoursup/export/index.js
server/src/jobs/parcoursup/tests/export.test.js

fix(psup): use cfd_entree !

---

server/src/logic/updaters/mnaFormationUpdater.js
ui/src/locales/helpText.json

https://trello.com/c/ykFwOc3Z/778-modif-sur-les-académies-de-rattachement
```bash
sudo docker exec catalogue_apprentissage_server bash -c "yarn trainings:updater --noUpdatesFilters"
```

fix: rollback academie

---

server/src/common/model/schema/formation/etablissement.formateur.sub.js
server/src/common/model/schema/formation/etablissement.gestionnaire.sub.js
server/src/common/model/schema/formation/formation.js
server/src/common/utils/paginator.js
server/src/jobs/index.js
server/src/jobs/parcoursup/coverage.js

bottleneck is mongodb driver, no need for multiple workers
1h --> 30 min

perf: faster ps coverage

---

server/src/common/esClient/mongoosastic/index.js
server/src/common/esClient/mongoosastic/serialize.js
server/src/common/utils/esUtils.js

~ 10x faster: reindex `formation` 4 minutes vs 40 minutes

perf: fast es index

---

server/src/logic/controller/coverage.js

https://trello.com/c/bJgUSvpL/905-inversion-de-règle-de-rapprochement

feat: change matching strength order for parcoursup

---

server/migrations/20220207134405-remove-info-depp-dgefp.js

Remove `info_depp`, `info_depp_info`, `info_dgefp`, `info_dgefp_info` fields.

clean: Add migration to remove infos linked to DEPP and DGEFP

---

server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
server/src/jobs/formations/rcoConverter/tests/migrationFinder.test.js

fix the way we search in ids actions
& add test with real data
:fire:

fix: find previous formation when key change

---

server/package.json
server/yarn.lock

Bump tco library to benefit from the following PRs :
- https://github.com/mission-apprentissage/tables-correspondances/pull/200 
- https://github.com/mission-apprentissage/tables-correspondances/pull/201

feat: bump tco

---

server/src/common/utils/parcoursupUtils.js
server/src/logic/updaters/mnaFormationUpdater.js

Since it will fail if we have invalid UAIs in DB
Also better error handling when PS MEF file is not uploaded

fix: no validate when creating sandbox formations

---

server/migrations/20220215151050-unique-index-consumption.js
server/src/common/model/schema/consumption.js
server/src/http/middlewares/consumptionMiddleware.js
server/src/http/middlewares/tryCatchMiddleware.js
server/src/http/server.js

Add method to consumption entity and ensure unicity for route/method attributes

fix: Amélioration du suivi de la consommation des APIs

---

server/migrations/20220221101750-update-consumption.js
server/src/common/model/schema/consumption.js
server/src/http/middlewares/consumptionMiddleware.js

- Ajout des dates sur les indices de consommation
- Remplace l'ip par le header Origin quand les appels sont effectués depuis un front
```sh
docker compose exec server yarn migration:up
```

feature: Add date and replace ip by origin if possible in consumptions collection

---

server/package.json
server/src/jobs/checkUai/index.js
server/src/jobs/index.js
server/src/jobs/oneshot/checkUai/index.js

- Retrait de l'envoi de mail puisque fait par le Metabase.
- Ajout du check lors des jobs nocturnes

feature: Add automatic job for UAIs check

---

ui/src/common/components/Search/Search.js

- translation
- fix pages display (legacy bug in reactiveList when results have 5 pages)
- also put page number in URL (for history navigation)

refactor: pagination

---

ui/src/common/components/Search/components/Pagination.jsx

Plus de numéros de pages quand on est proche de la première page :
Plus de numéros de pages quand on est proche de la fin:
Au milieu on garde comme avant :

feat: more digits on paging when close to start or close to end

---

ui/src/pages/Etablissement/Etablissement.js

:fire_engine: :fire_engine: :fire_engine:

fix: payload to update uai for etablissement

---

server/package.json
server/src/jobs/etablissements/EtablissementsUpdater/assets/sample.json
server/src/jobs/formations/rcoConverter/converter/converter.js
server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
server/src/jobs/formations/rcoConverter/tests/converter.test.js
server/src/jobs/formations/rcoConverter/tests/migrationFinder.test.js
server/src/jobs/formations/trainingsUpdater/updater/updater.js
server/src/logic/updaters/mnaFormationUpdater.js

[Suivi Trello](https://trello.com/c/VjRbu53t/957-adresse-calcul%C3%A9e-depuis-la-g%C3%A9oloc-ne-saffiche-pas-dans-tous-les-cas-il-faudrait)

fix: Adresse calculée depuis la géoloc ne s'affiche pas dans tous les cas. Il faudrait

---

server/src/common/model/swaggerSchema/formation.js
server/src/http/routes/etablissement.js

petit refactor car on utilise plus la pagination sur cette route

refactor: faster & cleaner siret-uai api

---

server/src/common/model/schema/etablissement.d.ts
server/src/logic/mappers/etablissementsMapper.js

chore: better typing

---

server/src/http/routes/parcoursup.js
server/tests/unit/logic/updaters/tagsHistoryUpdater.test.js
ui/src/common/components/Breadcrumb.jsx
ui/src/common/components/formation/PublishModal.jsx
ui/src/common/components/formation/PublishModal.test.js
ui/src/pages/admin/ReconciliationPs/components/ReconciliationModalHeader.jsx

tests & update `last_statut_update_date` on user actions

tests: add tests on tags history updater

---

server/package.json
server/src/jobs/etablissements/EtablissementsUpdater/index.js
server/src/jobs/etablissements/EtablissementsUpdater/updater/updater.js
server/src/jobs/oneshot/qualiopi/index.js
server/yarn.lock

feat: standalone script to update qualiopi data only

---

ui/src/common/components/formation/HistoryBlock.jsx
ui/src/common/components/formation/HistoryBlock.test.js
ui/src/pages/Formation/Formation.js

https://trello.com/c/nP1SIjqV/981-remont%C3%A9e-de-lhistorique-des-changements-de-statut-de-publication-utilisateurs-qui-sont-intervenus

feat: N'affiche que 5 éléments de l'historique par défaut

---

ui/src/common/components/Search/Search.js
ui/src/locales/helpText.json

https://trello.com/c/6c70waF2/738-ins%C3%A9rer-tooltip-sur-le-filtrage-dann%C3%A9es

feat: Tooltip d'information sur le champ de recherche 'Début de formation'

---

server/src/jobs/etablissements/EtablissementsUpdater/index.js
server/src/jobs/oneshot/qualiopi/index.js

update all, so that it can be closed, then reopened
```
docker exec catalogue_apprentissage_server bash -c "yarn etablissements:jobs -s"
```
https://trello.com/c/K3OR38v1/1017-siret-ouvert-dans-lapi-entreprises-mais-rejeté-dans-le-rapport-de-maj

fix: no closed establishment filter

---

server/package.json
server/src/common/mailer.js
server/yarn.lock
ui/package.json
ui/yarn.lock

chore: bump deps

---

server/src/jobs/affelnet/perimetre/controller.js
server/src/jobs/affelnet/tests/perimetre.test.js
server/tests/unit/common/utils/rulesUtils.test.js
ui/src/pages/Etablissement/Etablissement.test.js

https://trello.com/c/2nssRwjG/1027-formations-dont-le-mef-nest-pas-cohérent-avec-la-durée-collectée-peuvent-être-quand-même-dans-le-périmètre-affelnet

affelnet - bcn mefs check

---

ui/src/common/components/Search/Search.js
ui/src/common/components/Search/components/ExportButton.js

https://trello.com/c/aCNHtRoA/1058-sur-recette-tentatives-dexport-csv-non-sollicitées

fix: fix multiple downloads on reactive search query change

---

ui/src/common/components/HabiliteBadge.jsx
ui/src/common/components/Search/Search.js
ui/src/common/components/Search/components/CardListFormation/CardListFormation.js
ui/src/common/components/formation/OrganismesBlock.jsx

fix: N'affiche le badge Habilité RNCP que pour le catalogue Non règlementaire

---

ui/src/common/components/Search/constantsFormations.js
ui/src/common/components/formation/PublishModal.jsx
ui/src/pages/Formation/Formation.js

feat: Ajout d'un warning en cas de motif de dépublication sur la fiche Formation et dans les exports

---

server/package.json
server/src/http/routes/upload.js
server/yarn.lock

fix: sanitize upload filename

---

server/package.json
server/src/http/routes/auth.js
server/src/http/routes/password.js
server/src/http/server.js
server/tests/integration/http/login-test.js
server/tests/integration/http/password-test.js
server/yarn.lock

- 10 calls per second per IP
- 10 calls per minute for auth routes

fix: add rate limite to api routes

---

ui/src/common/components/Search/Search.js

https://trello.com/c/8Y8TGVJ0/1041-bug-de-tag

fix: search filters on switch search modes

---

server/src/http/server.js

https://trello.com/c/X5gclxsl/1101-erreur-de-compteur-dans-le-module-de-périmètre
:fire:

hotfix: API perimetre rate limit

---

ui/package.json
ui/src/common/components/formation/RejectionBlock.jsx
ui/yarn.lock

See https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined

fix: Resolution du problème en developpement 'process is not defined'

---

server/src/jobs/formations/dualControl/comparator.js
server/src/jobs/formations/dualControl/tests/comparator.test.js

https://trello.com/c/dPGpwDD1/1128-double-commande-vérifier-si-les-string-quon-reçoit-sont-bien-formatées

fix: mefs10 & subschema lean for comparison

---

server/src/jobs/formations/dualControl/parser.js
server/src/jobs/formations/dualControl/tests/parser.test.js

https://trello.com/c/dPGpwDD1/1128-double-commande-vérifier-si-les-string-quon-reçoit-sont-bien-formatées

fix: cfd closing date comparison
