mission-apprentissage/catalogue-apprentissage

server/src/jobs/rcoImporter/importer/importer.js

To prevent unnecessary db operations &  'null' updates in email report

fix: Update RCO formation in db only if it has some changes

---

server/package.json
server/src/jobs/oneshot/afFormation/importer.js
server/src/jobs/oneshot/afFormation/index.js
server/yarn.lock

92% de recouvrement des codes formations diplômes, trois méthodes : 
- Par le code MEF et les tables de correspondance
- Par le libellé de la formation et la table des formations converties (Algorithme _Indice de Sørensen-Dice_ - [npm](https://www.npmjs.com/package/string-similarity))
- Par le libellé de la formation et les tables de correspondance

feat: update importer

---

server/src/jobs/rcoConverter/converter/converter.js
server/src/jobs/trainingsUpdater/updater/updater.js
server/src/logic/mappers/etablissementsMapper.js
server/src/logic/updaters/mnaFormationUpdater.js

Remove uselless calls to code postal api + limit paginate to 10 items per batch
:warning: Il manque le **nom_departement** dans les établissements provenant des tables de correspondances. Pas très grave pour le moment vu qu'on ne l'utilise pas en front sur le catalogue, mais peut être que les clients de l'api catalogue en ont besoin.

perf(updater): spare calls to tco in updater

---

server/src/http/routes/convertedFormation.js

En ne retournant pas l'`updates_history`, on divise la payload retournée par 2 ~. 
En utilisant le `lean()` on gagne en mémoire et en perf.

perf(api): faster & lighter formations API

---

server/src/common/utils/esUtils.js

so that it rebuilds correctly index when mapping changes

feat: improve es:index script

---

server/src/jobs/pertinence/parcoursup/controller.js

this fix is only temporary, while we don't check the rncp certif/habilitation

hotfix: exclude rncp titre/tp from psup perimetre

---

server/src/logic/controller/reconciliation.js

And set affelnet value even if not found in bcn

fix: find mefs on 10 chars in reconciliation

---

server/src/http/routes/convertedFormation.js

Ajout d'un paramètre de requête pour l'API des formations, afin de filtrer par `id_parcoursup`. La fonctionnalité est à destination de l'application "Prise de rendez-vous".
eg: `/api/entity/formations2021?query={"id_parcoursup":26969}`
EDIT / Je renvoie à présent uniquement les formations pour lesquelles on a une seule occurrence par id parcoursup (1 pour 1 match fort)

feat(api): add id_parcoursup query param

---

server/src/jobs/affelnet/reconciliation.js
server/src/jobs/index.js

:warning: cela va impacter 494 formations "publié" Affelnet, et les passer en "à publier" ou "à publier (soumis à validation)".
Les académies vont être prévenues :
https://docs.google.com/spreadsheets/d/1408mdb7RG2MwqhjBPIpEZqCsfZtTh1dSXU9OZNtpuyM/edit?usp=sharing

feat(affelnet): reset reconciliation auto before running it

---

server/src/jobs/pertinence/affelnet/rules.js

voilà ce que ça donne avec les données de prod du 03/06/2021  (avant --> après):
```
Total formations hors périmètre : 17720/29181 --> 17773/29181 (+53)
Total formations à publier (soumis à validation) : 1266/29181 --> 1556/29181 (+290)
Total formations à publier : 3010/29181 --> 2667/29181  (-343)
Total formations en attente de publication : 974/29181 --> idem
Total formations publiées sur Affelnet : 4889/29181 --> idem
Total formations NON publiées sur Affelnet : 1322/29181 --> idem
```
On a moins de "à publier" (normal) et plus de "soumis à validation" et de hors périmètre. Ça me semble vraiment pas mal :slightly_smiling_face:

feat(affelnet): check cfd expiracy in pertinence rules

---

docker-compose.override.yml
ui/Dockerfile.dev

In Dockerfile.dev, execute yarn install in CMD instead of RUN as node…_modules is overwritten by a volume

Fix issue with node_modules overwritten by volume in devevelopment

---

ui/src/common/components/Search/constantsEtablissements.js

https://trello.com/c/YFYgVWnE/919-lexport-des-organismes-ne-comporte-pas-la-colonne-a-des-formations-de-niveau-3

bugfix: Ajout de la colonne 'A des formations n3' dans l'export des organismes

---

server/src/logic/controller/coverage.js

Inversion des deux règles suivantes car l'uai est plus précis que le code postal :
Avant
- m4 = mef + departement + code postal
- m3 = mef + departement + uai
Après
- m4 = mef + departement + uai
- m3 = mef + departement + code postal

feat(affelnet): reorder match strength

---

server/migrations/20220210162942-clean-parcoursup-formation-statuts-history.js
server/src/common/model/schema/parcoursupFormation.js
server/src/http/routes/parcoursup.js
server/src/jobs/parcoursup/reportRejected.js
server/src/logic/common/utils/diffUtils.js
server/src/logic/updaters/coverageUpdater.js
ui/src/pages/admin/ReconciliationPs/ReconciliationPs.test.js

Suppression de l'historique des rapprochements Parcoursup, et enregistrement des annulations de rapprochements validés dans l'historique des formations.
https://trello.com/c/3AP3zvY8/936-clean-données-dhistorisation-à-supprimer-ne-plus-stocker-historique-des-rapprochements-parcoursup

feat: clean status history PS

---

server/migrations/20220215110549-limit-history-affelnet-parcoursup.js
server/src/logic/updaters/tagsHistoryUpdater.js

200 éléments pour être sûr de couvrir la campagne affelnet (5-6 mois)

fix: keep 200 items in status history

---

server/migrations/20220216111515-add-published-dates.js
server/src/common/model/schema/formation/formation.js
server/src/common/model/swaggerSchema/formation.js
server/src/common/utils/historyUtils.js
server/src/http/routes/parcoursup.js
server/src/jobs/affelnet/perimetre/controller.js
server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
server/src/jobs/parcoursup/export/index.js
server/src/jobs/parcoursup/perimetre/controller.js
server/src/logic/controller/reconciliation.js
server/tests/unit/common/utils/historyUtils.test.js
ui/src/common/components/Search/Search.js
ui/src/common/components/Search/constantsFormations.js
ui/src/common/components/formation/PublishModal.jsx
ui/src/common/components/formation/PublishModal.test.js
ui/src/locales/helpText.json
ui/src/pages/Etablissement/Etablissement.js
ui/src/pages/Formation/Formation.js
ui/src/pages/admin/ReconciliationPs/components/ReconciliationModalHeader.jsx
ui/src/pages/layout/components/AlertMessage.js
ui/src/pages/layout/components/Header.js
ui/src/pages/layout/components/NavigationMenu.js

https://trello.com/c/GVUVtxOk/932-pouvoir-vérifier-les-publié-qui-ont-déjà-été-confirmée-via-date-de-modification-ou-horodatage-avec-possibilité-de-filtrage-par-p
Ajout de la date de publication pour Affelnet & Parcoursup, + filtrage & affichage sur la fiche formation.

feat: published dates

---

ui/src/pages/Formation/Formation.js

Affichage de l'erreur de publication via le web service Parcoursup sur la fiche formation :

feat: display parcoursup posting errors

---

server/src/jobs/affelnet/perimetre/controller.js
server/src/jobs/parcoursup/perimetre/controller.js

since non-qualiopi are in "catalogue général" don't reset status badges
https://trello.com/c/i0cysqz5/946-etiquette-affelnet-à-publier-persistante

fix: don't reset status badges for non-qualiopi

---

server/src/jobs/parcoursup/export/index.js
server/src/jobs/parcoursup/tests/export.test.js

https://trello.com/c/jFL1cmCI/903-envoyer-les-formations-sans-code-rncp-au-ws-ps

fix: no more filter on rncp for parcoursup

---

server/src/jobs/affelnet/coverage.js
server/src/jobs/affelnet/tests/coverage.test.js
server/src/logic/controller/coverage.js

https://trello.com/c/fi78Wd09/908-développer-le-flux-retour-incluant-les-clésme-pour-récupérer-le-statut-publié
Prise en compte des `cle_ministere_educatif` si elles sont présentes sur les lignes dans le fichier d'import Affelnet
**TODO :**

feat: affelnet import with key

---

server/src/jobs/affelnet/coverage.js
server/src/jobs/formations/rcoConverter/converter/converter.js
server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
server/src/jobs/formations/rcoConverter/tests/migrationFinder.test.js
server/src/logic/controller/reconciliation.js

https://trello.com/c/BU3h6420/967-changement-de-cléme-gestion-des-mono-site-multi-site
Question en cours pour la gestion de l'import de formations Affelnet devenues multi-site entre temps.
Réponse de @Anne-Becquet : 
> ah oui alors, donc se sont les 3 qui doivent être publiés, car sinon on envoie qu'une seule formation pour un CFA académique par exemple avec 1 seul UAI alors que potentiellement il faut en envoyer N. Je crois qu'Affelnet ne gère qu'un seul UAI mais peut créer des UAI lieux de formations si la DEPP les refuse. ...
TODO : 
~~DRAFT en attente de la réponse sur le nombre de sites possible (cf. mail Marc / Adeline)~~ Débloqué en gérant jusqu'à 99 lieux différents pour une même racine de clé.

fix: merge multi-site trainings on RCO key change

---

server/package.json
server/src/common/utils/streamUtils.js
server/yarn.lock

:fire: :fire_engine: Due to missing async/await throwing error in Node 16 in TCO lib
see https://github.com/mission-apprentissage/tables-correspondances/commit/e88b7b7efdcfdfbe69205ed2a6f8fa8d6934ec7d

fix: rncp import

---

server/src/http/server.js

To prevent csrf attacks
@see https://auth0.com/blog/cross-site-request-forgery-csrf/ &
https://cwe.mitre.org/data/definitions/1275.html &
https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie/SameSite

fix: session cookie is not sent when requests come from another domain

---

server/src/http/routes/etablissement.js
server/src/http/routes/formation.js
server/tests/integration/http/etablissement-test.js
server/tests/integration/http/formation.test.js

So that one may call :
```js
const response = await fetch("https://catalogue.apprentissage.beta.gouv.fr/api/v1/entity/formations.ndjson");
const data = await response.json();
...
```

fix: ndjson apis
